# Generated by Django 5.2.3 on 2025-07-30 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer', '0002_loginattempt_lecturer_email_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='verification_code_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
