# Generated by Django 5.2.3 on 2025-08-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer', '0003_lecturer_verification_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='email_change_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='email_change_token_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='new_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
