# Generated by Django 5.2.3 on 2025-08-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer', '0004_lecturer_email_change_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='account_locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='failed_login_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='last_failed_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
